namespace GameCollector.Server.Utils;

using System.Collections.ObjectModel;
using Models;
using static Species;

public static class GenderDependents
{
    public static readonly Collection<GenderDependent> Species =
    [
        new GenderDependent(Venusaur, 0),
        new GenderDependent(Butterfree, 0),
        new GenderDependent(Rattata, 0),
        new GenderDependent(Raticate, 0),
        new GenderDependent(Pikachu, 0),
        new GenderDependent(Raichu, 0),
        new GenderDependent(Zubat, 0),
        new GenderDependent(Golbat, 0),
        new GenderDependent(Gloom, 0),
        new GenderDependent(Vileplume, 0),
        new GenderDependent(Kadabra, 0),
        new GenderDependent(Alakazam, 0),
        new GenderDependent(Doduo, 0),
        new GenderDependent(Dodrio, 0),
        new GenderDependent(Hypno, 0),
        new GenderDependent(Rhyhorn, 0),
        new GenderDependent(Rhydon, 0),
        new GenderDependent(Goldeen, 0),
        new GenderDependent(Seaking, 0),
        new GenderDependent(Scyther, 0),
        new GenderDependent(Magikarp, 0),
        new GenderDependent(Gyarados, 0),
        new GenderDependent(Eevee, 0),
        new GenderDependent(Meganium, 0),
        new GenderDependent(Ledyba, 0),
        new GenderDependent(Ledian, 0),
        new GenderDependent(Xatu, 0),
        new GenderDependent(Sudowoodo, 0),
        new GenderDependent(Politoed, 0),
        new GenderDependent(Aipom, 0),
        new GenderDependent(Wooper, 0),
        new GenderDependent(Quagsire, 0),
        new GenderDependent(Murkrow, 0),
        new GenderDependent(Wobbuffet, 0),
        new GenderDependent(Girafarig, 0),
        new GenderDependent(Gligar, 0),
        new GenderDependent(Steelix, 0),
        new GenderDependent(Scizor, 0),
        new GenderDependent(Heracross, 0),
        new GenderDependent(Sneasel, 0),
        new GenderDependent(Sneasel, 1),
        new GenderDependent(Ursaring, 0),
        new GenderDependent(Piloswine, 0),
        new GenderDependent(Octillery, 0),
        new GenderDependent(Houndoom, 0),
        new GenderDependent(Donphan, 0),
        new GenderDependent(Torchic, 0),
        new GenderDependent(Combusken, 0),
        new GenderDependent(Blaziken, 0),
        new GenderDependent(Beautifly, 0),
        new GenderDependent(Dustox, 0),
        new GenderDependent(Ludicolo, 0),
        new GenderDependent(Nuzleaf, 0),
        new GenderDependent(Shiftry, 0),
        new GenderDependent(Meditite, 0),
        new GenderDependent(Medicham, 0),
        new GenderDependent(Roselia, 0),
        new GenderDependent(Gulpin, 0),
        new GenderDependent(Swalot, 0),
        new GenderDependent(Numel, 0),
        new GenderDependent(Camerupt, 0),
        new GenderDependent(Cacturne, 0),
        new GenderDependent(Milotic, 0),
        new GenderDependent(Relicanth, 0),
        new GenderDependent(Starly, 0),
        new GenderDependent(Staravia, 0),
        new GenderDependent(Staraptor, 0),
        new GenderDependent(Bidoof, 0),
        new GenderDependent(Bibarel, 0),
        new GenderDependent(Kricketot, 0),
        new GenderDependent(Kricketune, 0),
        new GenderDependent(Shinx, 0),
        new GenderDependent(Luxio, 0),
        new GenderDependent(Luxray, 0),
        new GenderDependent(Roserade, 0),
        new GenderDependent(Combee, 0),
        new GenderDependent(Pachirisu, 0),
        new GenderDependent(Floatzel, 0),
        new GenderDependent(Buizel, 0),
        new GenderDependent(Ambipom, 0),
        new GenderDependent(Gible, 0),
        new GenderDependent(Gabite, 0),
        new GenderDependent(Garchomp, 0),
        new GenderDependent(Hippopotas, 0),
        new GenderDependent(Hippowdon, 0),
        new GenderDependent(Croagunk, 0),
        new GenderDependent(Toxicroak, 0),
        new GenderDependent(Finneon, 0),
        new GenderDependent(Lumineon, 0),
        new GenderDependent(Snover, 0),
        new GenderDependent(Abomasnow, 0),
        new GenderDependent(Weavile, 0),
        new GenderDependent(Rhyperior, 0),
        new GenderDependent(Tangrowth, 0),
        new GenderDependent(Mamoswine, 0),
        new GenderDependent(Unfezant, 0),
        new GenderDependent(Frillish, 0),
        new GenderDependent(Jellicent, 0),
        new GenderDependent(Pyroar, 0),
        new GenderDependent(Basculegion, 0),
        new GenderDependent(Enamorus, 0)
    ];
}
